name: Deploy AutomÃ¡tico (OTA Update)

on:
  push:
    branches:
      - main 

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup do RepositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ— Setup do Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: ğŸ“¦ Instalar EAS CLI
        run: npm install -g eas-cli

      - name: ğŸ“¦ Instalar DependÃªncias
        run: npm install

      - name: ğŸš€ Publicar AtualizaÃ§Ã£o (Preview)
        run: eas update --branch preview --message "${{ github.event.head_commit.message }}"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}